models/Training.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "training".
 *
 * @property int $id
 * @property int $exercise_id
 * @property double $weight
 * @property int $repitition
 * @property int $approach
 * @property int $trener_id
 * @property int $coaching_id
 * @property int $with
 *
 * @property Coaching $coaching
 * @property Exercise $exercise
 * @property Users $trener
 */
class Training extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'training';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['exercise_id'], 'required'],
            [['exercise_id', 'repitition', 'approach', 'trener_id', 'coaching_id', 'with'], 'integer'],
            [['weight'], 'string', 'max' => 255],
            [['exercise_id'], 'exist', 'skipOnError' => true, 'targetClass' => Exercise::class, 'targetAttribute' => ['exercise_id' => 'id']],
            [['trener_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::class, 'targetAttribute' => ['trener_id' => 'id']],
            [['coaching_id'], 'exist', 'skipOnError' => true, 'targetClass' => Coaching::class, 'targetAttribute' => ['coaching_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'exercise_id' => 'Название упражнения',
            'weight' => 'Вес',
            'repitition' => 'Количество повторений ',
            'approach' => 'Количество подходов',
            'with' => 'Объединить с',
            'trener_id' => 'Тренер',
            'coaching_id' => 'Coaching ID',
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
        {
            $this->trener_id = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCoaching()
    {
        return $this->hasOne(Coaching::class, ['id' => 'coaching_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExercise()
    {
        return $this->hasOne(Exercise::class, ['id' => 'exercise_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTrener()
    {
        return $this->hasOne(Users::class, ['id' => 'trener_id']);
    }

    public function getExerciseList()
    {
        $exercise = Exercise::find()->all();
        return ArrayHelper::map( $exercise , 'id', 'name');
    }
}

controllers/TrainingController.php
<?php

namespace app\controllers;

use app\models\CoachingCompleting;
use app\models\CoachingUsers;
use app\models\Exercise;
use app\models\Users;
use Codeception\Command\Completion;
use Yii;
use app\models\Training;
use app\models\TrainingSearch;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\Coaching;

/**
 * TrainingController implements the CRUD actions for Training model.
 */
class TrainingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Training models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TrainingSearch();
        $dataProvider = $searchModel->searchCoach(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * @return mixed
     */
    public function actionCoachingsUsers()
    {
        $usersPks = ArrayHelper::getColumn(Users::find()->where(['permission' => 'client', 'trener' => Yii::$app->user->getId()])->all(), 'id');
        $coachingPks = ArrayHelper::getColumn(Coaching::find()->where(['trener_id' => Yii::$app->user->getId()])->all(), 'id');
        $coachingUsers = CoachingUsers::find()->where(['users_id' => $usersPks, 'coaching_id' => $coachingPks])->with('users')->with('coaching')->all();

        return $this->render('coachings-users', [
            'coachingUsers' => $coachingUsers,
        ]);
    }

    public function actionTrainingList()
    {
//        $searchModel = new TrainingSearch();
//        $dataProvider = $searchModel->searchCoach(Yii::$app->request->queryParams);
        $trainings = new Users();
        $trainings = $trainings->getTrainings();
        return $this->render('training-list', [
//            'searchModel' => $searchModel,
            'trainings' => $trainings,
        ]);
    }

    /**
     * @throws BadRequestHttpException
     * @return array
     */
    public function actionSendClientRequest()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        if(isset($_POST['trainer_id']) == false){
            throw new BadRequestHttpException();
        }
        $trainer_id = $_POST['trainer_id'];

        /** @var Users $user */
        $user = Yii::$app->user->identity;

        $result = $user->sendRequest($trainer_id);

        return ['result' => $result];
    }

    public function actionClientView()
    {
        return $this->render('client-view', [
//            'trainings' => $trainings,
        ]);
    }

    /**
     * @throws BadRequestHttpException
     * @return array
     */
    public function actionMakeCoachingCompleted()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        if(isset($_POST['coaching_id']) == false){
            throw new BadRequestHttpException();
        }
        $coaching_id = $_POST['coaching_id'];
        /** @var Coaching $coaching */
        $coaching = $this->findCoaching($coaching_id);

        $result = $coaching->makeCompleted();

        return ['result' => $result];
    }

    /**
     * Displays a single Training model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        $model = $this->findCoaching($id);
        $trainnings = Training::find()->where(['coaching_id' => $model->id])->orderBy('id asc')->all();
        $exercisesIds = array_values(ArrayHelper::map($trainnings, 'id', 'exercise_id'));
        $exercisesData = Exercise::findAll($exercisesIds);
        $exercises = ArrayHelper::map($exercisesData, 'id', 'name');
        $exercisesGroups = ArrayHelper::map($exercisesData, 'id', 'exercise_group_id');
        $exercisesTrainnings = [];

        // Делаем карту {ExerciseId} => Training
        foreach ($exercises as $id => $name)
        {
            foreach ($trainnings as $trainning)
            {
                if($trainning->exercise_id == $id)
                {
                    $exercisesTrainnings[$id] = $trainning;
                }
            }
        }

        /** @var Training[] $coachingTrainings */
        $coachingTrainings = $trainnings;

        $trainingUnions = [];

        foreach ($coachingTrainings as $training){
            if($training->with != null){
                $trainingUnions[$training->with][] = $training->id;
            } else {
                $trainingUnions[$training->id][] = $training->id;
            }
        }

        ksort($exercises);
        // exit;

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title' => "Тренировка",
                'size' => 'normal',
                'content' => $this->renderAjax('view', [
                    'model' => $model,
                    'trainnings' => $trainnings,
                    'exercisesGroups' => $exercisesGroups,
                    'exercises' => $exercises,
                    'exercisesTrainnings' => $exercisesTrainnings,
                    'trainingUnions' => $trainingUnions,
                ]),
                'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                    Html::a('Изменить', ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
            ];
        } else {

            return $this->render('view', [
                'model' => $model,
                'trainnings' => $trainnings,
                'exercisesGroups' => $exercisesGroups,
                'exercises' => $exercises,
                'exercisesTrainnings' => $exercisesTrainnings,
                'trainingUnions' => $trainingUnions,
            ]);
        }
    }

    /**
     * Creates a new Training model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAddCoach()
    {
        $request = Yii::$app->request;
        $model = new Coaching();

        if ($model->load($request->post()) && $model->save()) {
            if($request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return [
                    'forceReload' => '#calls-datatable-pjax',
                    'title' => "Тренировка",
                    'forceClose' => true,
                ];
            } else {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {

            if($request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return [
                    'title' => "Создать",
                    'size' => 'normal',
                    'content' => $this->renderAjax('add-coach', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                ];
            } else {
                return $this->render('add-coach', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing Training model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateCoach($id)
    {
        $request = Yii::$app->request;
        $model = $this->findCoaching($id);

        if ($model->load($request->post()) && $model->save()) {
            if($request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return [
                    'forceReload' => '#calls-datatable-pjax',
                    'title' => "Тренировка",
                    'forceClose' => true,
                ];
            } else {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {

            if($request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return [
                    'title' => "Создать",
                    'size' => 'normal',
                    'content' => $this->renderAjax('add-coach', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])

                ];
            } else {
                return $this->render('add-coach', [

views/training/_coach_columns.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use kartik\grid\GridView;
return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'kartik\grid\ExpandRowColumn', 
        'width'=>'50px',
        'value'=>function ($model, $key, $index, $column) {
            return GridView::ROW_COLLAPSED;
        },
        'detail'=>function ($model, $key, $index, $column) {
            return \Yii::$app->controller->renderPartial('_expand-training', ['model'=>$model]);
        },
        'headerOptions'=>['class'=>'kartik-sheet-style'],
        'expandOneOnly'=>true
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'description',
        'format'=>'html', 
    ], 
    [
        'attribute'=>'id',
        'header' => 'Добавить',
        'class'=>'\kartik\grid\DataColumn',
        'content' => function ($data) 
        {
            return '&nbsp;&nbsp;&nbsp;&nbsp;<a style="font-size:10px" class="btn btn-primary" role="modal-remote" href="'.Url::toRoute(['/training/add', 'trener_id' => $data->trener_id, 'coaching_id' => $data->id, ]).'"><i class="glyphicon glyphicon-plus"></i></a>';
        },
    ],
    [
        'class'    => 'kartik\grid\ActionColumn',
        'template' => '{leadUpdate} {leadDelete}',
        'buttons'  => [
            'leadUpdate' => function ($url, $model) {
                $url = Url::to(['/training/update-coach', 'id' => $model->id]);
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip']);
            },
            'leadDelete' => function ($url, $model) {
                $url = Url::to(['/training/coach-remove', 'id' => $model->id]);
                return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                    'role'=>'modal-remote','title'=>'', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Подтвердите действие',
                          'data-confirm-message'=>'Вы уверены что хотите удалить этот элемент?'
                ]);
            },
        ]
    ]

];   

views/training/_columns.php
<?php
use yii\helpers\Url;
use app\models\Users;
use yii\helpers\ArrayHelper;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'exercise_id',
        'content' => function($data){
            return $data->exercise->name;
        }
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'weight',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'repitition',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'approach',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'trener_id',
        'filter' => ArrayHelper::map(Users::find()->where(['permission' => Users::USER_ROLE_TRENER])->all(),'id','fio'),
        'content' => function($data){
            return $data->trener->fio;
        }
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Are you sure?',
                          'data-confirm-message'=>'Are you sure want to delete this item'], 
    ],

];   

views/training/_expand-training.php
<?php
/**
 * Created by PhpStorm.
 * User: Ilusha
 * Date: 06.05.2017
 * Time: 13:38
 */

use kartik\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;

?>

<?=GridView::widget([
    'id'=>'crud-datatable',
    'responsiveWrap' => false,
    'dataProvider' => $model->orderTrainingData,
    'columns' => [
        [
            'class' => 'kartik\grid\SerialColumn',
            'width' => '30px',
        ],
        [
            'class'=>'\kartik\grid\DataColumn', 
            'attribute'=>'exercise_id',
            'content' => function ($data) {
                return $data->exercise->name;
            },
        ],
        'weight',
        'repitition',
        'approach',
        [
            'class'=>'\kartik\grid\DataColumn',
            'attribute'=>'trener_id',
            'content' => function($data){
                return $data->trener->fio;
            }
        ],
        [
            'class'    => 'kartik\grid\ActionColumn',
            'template' => '{leadDelete}',
            'buttons'  => [
                
                'leadUpdate' => function ($url, $model) {
                    $url = Url::to(['/goods/update-goods', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, ['role'=>'modal-remote','title'=>'', 'data-toggle'=>'tooltip']);
                },
                'leadDelete' => function ($url, $model) {
                    $url = Url::to(['/training/remove', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                        'role'=>'modal-remote','title'=>'', 
                              'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                              'data-request-method'=>'post',
                              'data-toggle'=>'tooltip',
                              'data-confirm-title'=>'Подтвердите действие',
                              'data-confirm-message'=>'Вы уверены что хотите удалить этот элемент?'
                    ]);
                },
            ]
        ]
    ],
    'striped' => true,
    'condensed' => true,
    'responsive' => true,
])?>

views/training/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Training */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="training-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'exercise_id')->dropDownList($model->getExerciseList(), ['prompt' => 'Выберите упражнение' ]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'weight')->textInput([]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'repitition')->textInput(['type' => 'number']) ?>            
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'approach')->textInput(['type' => 'number']) ?>
        </div>
    </div>
  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/training/add-coach.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use mihaildev\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\Training */
/* @var $form yii\widgets\ActiveForm */

$this->params['header-action-button'] = Html::a('<i class="fa fa-check"></i>', '#', ['onclick' => 'event.preventDefault(); $("#main-form").submit();']);

?>

<div class="training-form">

    <?php $form = ActiveForm::begin(['id' => 'main-form']); ?>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-12">
            <?= $form->field($model, 'description')->widget(CKEditor::className(),[
                'editorOptions' => [
                    'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                    'inline' => false, //по умолчанию false
                    'height' => '150px',
                ],
            ]);
            ?>
        </div>
    </div>
  
    <?php ActiveForm::end(); ?>
    
</div>

views/training/add_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Training */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="training-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'exercise_id')->dropDownList($model->getExerciseList(), ['prompt' => 'Выберите упражнение' ]) ?>
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'weight')->textInput([]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'repitition')->textInput(['type' => 'number']) ?>            
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'approach')->textInput(['type' => 'number']) ?>
        </div>
    </div>
  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/training/add_training.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Exercise;

/** @var $this \yii\web\View */
/** @var $model \app\models\Training */
/** @var $coaching \app\models\Coaching */

$this->title = 'Добавить упражнение';

$this->params['header-action-button'] = Html::a('<i class="fa fa-check"></i>', '#', ['onclick' => 'event.preventDefault(); $("#main-form").submit();']);

$exercisesPks = $coaching->getUsingExercisesPks();

if($model->isNewRecord == false) {
    $exercisesPks = array_filter($exercisesPks, function($el) use($model){
        return $el != $model->exercise_id;
    });
}

$exercises = ArrayHelper::map(Exercise::find()->where(['not in', 'id', $exercisesPks])->with('exerciseGroup')->all(), 'id', 'name', 'exerciseGroup.name');

$withMap = [];

foreach ($trainingUnions as $key => $value){
    $newValues = [];
    if(is_array($value)){
        foreach ($value as $row){
            $exercise = Exercise::findOne($row);
            if($exercise) {
                $newValues[] = $exercise->name;
            }
        }
        $withMap[$key] = implode(',', $newValues);
    } else {
        $exercise = Exercise::findOne($value);
        if($exercise) {
            $withMap[$key] = $exercise->name;
        }
    }
}

?>

<?php $form = ActiveForm::begin(['id' => 'main-form']); ?>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'exercise_id')->dropDownList($exercises, ['prompt' => 'Выберите упражнение']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'with')->dropDownList($withMap, ['prompt' => 'Выберите упражнения']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'weight')->textInput(['type' => 'number']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'repitition')->textInput(['type' => 'number']) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'approach')->textInput(['type' => 'number']) ?>
        </div>
    </div>

<?php ActiveForm::end(); ?>

views/training/coachings-users.php
<?php

use yii\helpers\Html;

/** @var \app\models\CoachingUsers[] $coachingUsers */

?>

<ul class="items-list">
        <?php foreach ($coachingUsers as $coachingUser): ?>
            <li>
                <?=Html::a($coachingUser->coaching->name."<br>Клиент: {$coachingUser->users->fio}", ['training/view', 'id' => $coachingUser->coaching->id], ['class' => 'list-item', 'style' => 'width: 100%;'])?>
            </li>
        <?php endforeach; ?>
</ul>

views/training/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Training */

?>
<div class="training-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/training/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;
use app\models\CoachingCompleting;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AtelierSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Тренировка';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

if(Yii::$app->user->identity->permission == \app\models\Users::USER_ROLE_TRENER) {
    $this->params['header-action-button'] = Html::a('<i class="fa fa-plus"></i>', ['add-coach']);
}

?>

<?php \yii\widgets\Pjax::begin(['id' => 'crud-list-pjax', 'enablePushState' => false]) ?>
<?php \app\assets\plugins\TouchSwipeAsset::register($this); ?>
<ul class="items-list">
    <?php foreach ($dataProvider->models as $model): ?>
        <li>
            <?php   $trener = \app\models\Users::find()->where(['id' => $model->trener_id])->one();
                    if($trener != null) {
                        $trenerName = $trener->fio;
                    } else {
                        $trenerName = null;
                    }
                    $completedCount = CoachingCompleting::find()->where(['coaching_id' => $model->id, 'client_id' => Yii::$app->user->getId()])->count();
            ?>
            <?= Html::a($model->name.'<br><span style="font-size: 12px;"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span style="font-size: 12px;">Выполнена '.$completedCount.' '.\php_rutils\RUtils::numeral()->choosePlural($completedCount, ['раз', 'раза', 'раз']).'</span><br>
                    <span style="font-size: 12px;">Тренер: '.$trenerName.'</span>',
                ['view', 'id' => $model->id], ['class' => 'list-item', 'style' => 'width: 100%;', 'data-pjax' => 0]) ?>
            <?php if(Yii::$app->user->identity->permission != \app\models\Users::USER_ROLE_CLIENT): ?>
                <a class="item-action item-success" href="<?=Url::toRoute(['update-coach', 'id' => $model->id])?>" data-pjax="0"><i class="fa fa-pencil"></i></a>
                <?= Html::a('<i class="fa fa-trash"></i>', ['delete-coach', 'id' => $model->id], ['class' => "item-action item-danger",
                    'role'=>'modal-remote','title'=>'Удалить',
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-toggle'=>'tooltip',
                    'data-confirm-title'=>'Подтвердите действие',
                    'data-confirm-message'=>'Вы уверены что хотите удалить этот элемент?'
                ]) ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php

if(Yii::$app->user->identity->permission != \app\models\Users::USER_ROLE_CLIENT)
{
    $this->registerJs(file_get_contents('js/scripts/list-swipe.js'), \yii\web\View::POS_READY);
}


?>
<?php \yii\widgets\Pjax::end()?>


<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/training/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Training */
?>
<div class="training-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>